import re
from common.resource_info import ResourceInfo

__author__ = 'CoYe'

device_data = {}
device_data['port_list'] = """RTRV-CFG-FIBER::10001&&10048&20001&&20048:1;

   BD0472 16-06-09 17:12:52
M  1 COMPLD
   "GGN:PORTID=10001,PORTGROUP=OpenGroup,PORTNAME=IN1,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10002,PORTGROUP=OpenGroup,PORTNAME=IN2,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10003,PORTGROUP=OpenGroup,PORTNAME=IN3,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10004,PORTGROUP=OpenGroup,PORTNAME=IN4,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10005,PORTGROUP=OpenGroup,PORTNAME=IN5,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10006,PORTGROUP=OpenGroup,PORTNAME=IN6,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10007,PORTGROUP=OpenGroup,PORTNAME=IN7,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10008,PORTGROUP=OpenGroup,PORTNAME=IN8,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10009,PORTGROUP=OpenGroup,PORTNAME=IN9,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10010,PORTGROUP=OpenGroup,PORTNAME=IN10,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10011,PORTGROUP=OpenGroup,PORTNAME=IN11,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10012,PORTGROUP=OpenGroup,PORTNAME=IN12,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10013,PORTGROUP=OpenGroup,PORTNAME=IN13,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10014,PORTGROUP=OpenGroup,PORTNAME=IN14,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10015,PORTGROUP=OpenGroup,PORTNAME=IN15,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10016,PORTGROUP=OpenGroup,PORTNAME=IN16,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10017,PORTGROUP=OpenGroup,PORTNAME=IN17,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10018,PORTGROUP=OpenGroup,PORTNAME=IN18,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10019,PORTGROUP=OpenGroup,PORTNAME=IN19,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10020,PORTGROUP=OpenGroup,PORTNAME=IN20,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10021,PORTGROUP=OpenGroup,PORTNAME=IN21,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10022,PORTGROUP=OpenGroup,PORTNAME=IN22,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10023,PORTGROUP=OpenGroup,PORTNAME=IN23,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10024,PORTGROUP=OpenGroup,PORTNAME=IN24,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10025,PORTGROUP=OpenGroup,PORTNAME=IN25,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10026,PORTGROUP=OpenGroup,PORTNAME=IN26,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
>
<

   BD0472 16-06-09 17:12:52
M  1 COMPLD
   "GGN:PORTID=10027,PORTGROUP=OpenGroup,PORTNAME=IN27,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10028,PORTGROUP=OpenGroup,PORTNAME=IN28,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10029,PORTGROUP=OpenGroup,PORTNAME=IN29,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10030,PORTGROUP=OpenGroup,PORTNAME=IN30,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10031,PORTGROUP=OpenGroup,PORTNAME=IN31,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10032,PORTGROUP=OpenGroup,PORTNAME=IN32,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10033,PORTGROUP=OpenGroup,PORTNAME=IN33,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10034,PORTGROUP=OpenGroup,PORTNAME=IN34,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10035,PORTGROUP=OpenGroup,PORTNAME=IN35,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10036,PORTGROUP=OpenGroup,PORTNAME=IN36,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10037,PORTGROUP=OpenGroup,PORTNAME=IN37,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10038,PORTGROUP=OpenGroup,PORTNAME=IN38,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10039,PORTGROUP=OpenGroup,PORTNAME=IN39,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10040,PORTGROUP=OpenGroup,PORTNAME=IN40,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10041,PORTGROUP=OpenGroup,PORTNAME=IN41,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10042,PORTGROUP=OpenGroup,PORTNAME=IN42,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10043,PORTGROUP=OpenGroup,PORTNAME=IN43,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10044,PORTGROUP=OpenGroup,PORTNAME=IN44,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10045,PORTGROUP=OpenGroup,PORTNAME=IN45,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10046,PORTGROUP=OpenGroup,PORTNAME=IN46,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10047,PORTGROUP=OpenGroup,PORTNAME=IN47,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=10048,PORTGROUP=OpenGroup,PORTNAME=IN48,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI"
   "GGN:PORTID=20001,PORTGROUP=OpenGroup,PORTNAME=OUT1,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20002,PORTGROUP=OpenGroup,PORTNAME=OUT2,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20003,PORTGROUP=OpenGroup,PORTNAME=OUT3,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20004,PORTGROUP=OpenGroup,PORTNAME=OUT4,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
>
<

   BD0472 16-06-09 17:12:52
M  1 COMPLD
   "GGN:PORTID=20005,PORTGROUP=OpenGroup,PORTNAME=OUT5,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20006,PORTGROUP=OpenGroup,PORTNAME=OUT6,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20007,PORTGROUP=OpenGroup,PORTNAME=OUT7,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20008,PORTGROUP=OpenGroup,PORTNAME=OUT8,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20009,PORTGROUP=OpenGroup,PORTNAME=OUT9,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20010,PORTGROUP=OpenGroup,PORTNAME=OUT10,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20011,PORTGROUP=OpenGroup,PORTNAME=OUT11,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20012,PORTGROUP=OpenGroup,PORTNAME=OUT12,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20013,PORTGROUP=OpenGroup,PORTNAME=OUT13,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20014,PORTGROUP=OpenGroup,PORTNAME=OUT14,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20015,PORTGROUP=OpenGroup,PORTNAME=OUT15,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20016,PORTGROUP=OpenGroup,PORTNAME=OUT16,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20017,PORTGROUP=OpenGroup,PORTNAME=OUT17,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20018,PORTGROUP=OpenGroup,PORTNAME=OUT18,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20019,PORTGROUP=OpenGroup,PORTNAME=OUT19,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20020,PORTGROUP=OpenGroup,PORTNAME=OUT20,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20021,PORTGROUP=OpenGroup,PORTNAME=OUT21,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20022,PORTGROUP=OpenGroup,PORTNAME=OUT22,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20023,PORTGROUP=OpenGroup,PORTNAME=OUT23,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20024,PORTGROUP=OpenGroup,PORTNAME=OUT24,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20025,PORTGROUP=OpenGroup,PORTNAME=OUT25,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20026,PORTGROUP=OpenGroup,PORTNAME=OUT26,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20027,PORTGROUP=OpenGroup,PORTNAME=OUT27,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20028,PORTGROUP=OpenGroup,PORTNAME=OUT28,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
>
<

   BD0472 16-06-09 17:12:52
M  1 COMPLD
   "GGN:PORTID=20029,PORTGROUP=OpenGroup,PORTNAME=OUT29,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20030,PORTGROUP=OpenGroup,PORTNAME=OUT30,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20031,PORTGROUP=OpenGroup,PORTNAME=OUT31,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20032,PORTGROUP=OpenGroup,PORTNAME=OUT32,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20033,PORTGROUP=OpenGroup,PORTNAME=OUT33,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20034,PORTGROUP=OpenGroup,PORTNAME=OUT34,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20035,PORTGROUP=OpenGroup,PORTNAME=OUT35,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20036,PORTGROUP=OpenGroup,PORTNAME=OUT36,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20037,PORTGROUP=OpenGroup,PORTNAME=OUT37,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20038,PORTGROUP=OpenGroup,PORTNAME=OUT38,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20039,PORTGROUP=OpenGroup,PORTNAME=OUT39,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20040,PORTGROUP=OpenGroup,PORTNAME=OUT40,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20041,PORTGROUP=OpenGroup,PORTNAME=OUT41,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20042,PORTGROUP=OpenGroup,PORTNAME=OUT42,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20043,PORTGROUP=OpenGroup,PORTNAME=OUT43,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20044,PORTGROUP=OpenGroup,PORTNAME=OUT44,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20045,PORTGROUP=OpenGroup,PORTNAME=OUT45,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20046,PORTGROUP=OpenGroup,PORTNAME=OUT46,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20047,PORTGROUP=OpenGroup,PORTNAME=OUT47,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
   "GGN:PORTID=20048,PORTGROUP=OpenGroup,PORTNAME=OUT48,SIGBAND=1550,SIGTHRESH=1550,PORTHEALTH=good,PORTCAT=nor,PORTCOMMENT=,STMINSEV=DI,STMAXSEV=DI,CSFLTSEV=CR"
;"""

device_data["connections_map"] = """   BD0472 16-06-09 17:13:36
M  1 COMPLD
   "GGN:IPORTID=10001,IPORTGROUP=OpenGroup,IPORTNAME=IN1,IPORTCOMMENT=,INPWR=-12.05,OPORTID=20008,OPORTGROUP=OpenGroup,OPORTNAME=OUT8,OPORTCOMMENT=,OUTPWR=-13.63,SIGBAND=1550,PWRLOSS=1.57,CONNID=0,CONNNAME=IN1,CONNSTATE=steady,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER=admin"
   "GGN:IPORTID=10002,IPORTGROUP=OpenGroup,IPORTNAME=IN2,IPORTCOMMENT=,INPWR=-12.50,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10003,IPORTGROUP=OpenGroup,IPORTNAME=IN3,IPORTCOMMENT=,INPWR=-13.02,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10004,IPORTGROUP=OpenGroup,IPORTNAME=IN4,IPORTCOMMENT=,INPWR=-11.93,OPORTID=20005,OPORTGROUP=OpenGroup,OPORTNAME=OUT5,OPORTCOMMENT=,OUTPWR=-13.51,SIGBAND=1550,PWRLOSS=1.58,CONNID=0,CONNNAME=IN4,CONNSTATE=steady,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER=admin"
   "GGN:IPORTID=10005,IPORTGROUP=OpenGroup,IPORTNAME=IN5,IPORTCOMMENT=,INPWR=-50.66,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10006,IPORTGROUP=OpenGroup,IPORTNAME=IN6,IPORTCOMMENT=,INPWR=-49.67,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10007,IPORTGROUP=OpenGroup,IPORTNAME=IN7,IPORTCOMMENT=,INPWR=-49.54,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10008,IPORTGROUP=OpenGroup,IPORTNAME=IN8,IPORTCOMMENT=,INPWR=-49.78,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10009,IPORTGROUP=OpenGroup,IPORTNAME=IN9,IPORTCOMMENT=,INPWR=-50.25,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10010,IPORTGROUP=OpenGroup,IPORTNAME=IN10,IPORTCOMMENT=,INPWR=-50.98,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10011,IPORTGROUP=OpenGroup,IPORTNAME=IN11,IPORTCOMMENT=,INPWR=-50.24,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10012,IPORTGROUP=OpenGroup,IPORTNAME=IN12,IPORTCOMMENT=,INPWR=-50.64,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10013,IPORTGROUP=OpenGroup,IPORTNAME=IN13,IPORTCOMMENT=,INPWR=-50.78,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10014,IPORTGROUP=OpenGroup,IPORTNAME=IN14,IPORTCOMMENT=,INPWR=-50.99,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10015,IPORTGROUP=OpenGroup,IPORTNAME=IN15,IPORTCOMMENT=,INPWR=-49.91,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10016,IPORTGROUP=OpenGroup,IPORTNAME=IN16,IPORTCOMMENT=,INPWR=-50.39,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
>
<

   BD0472 16-06-09 17:13:36
M  1 COMPLD
   "GGN:IPORTID=10017,IPORTGROUP=OpenGroup,IPORTNAME=IN17,IPORTCOMMENT=,INPWR=-49.87,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10018,IPORTGROUP=OpenGroup,IPORTNAME=IN18,IPORTCOMMENT=,INPWR=-50.43,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10019,IPORTGROUP=OpenGroup,IPORTNAME=IN19,IPORTCOMMENT=,INPWR=-50.39,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10020,IPORTGROUP=OpenGroup,IPORTNAME=IN20,IPORTCOMMENT=,INPWR=-50.64,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10021,IPORTGROUP=OpenGroup,IPORTNAME=IN21,IPORTCOMMENT=,INPWR=-50.18,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10022,IPORTGROUP=OpenGroup,IPORTNAME=IN22,IPORTCOMMENT=,INPWR=-50.01,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10023,IPORTGROUP=OpenGroup,IPORTNAME=IN23,IPORTCOMMENT=,INPWR=-50.11,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10024,IPORTGROUP=OpenGroup,IPORTNAME=IN24,IPORTCOMMENT=,INPWR=-49.75,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10025,IPORTGROUP=OpenGroup,IPORTNAME=IN25,IPORTCOMMENT=,INPWR=-13.04,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10026,IPORTGROUP=OpenGroup,IPORTNAME=IN26,IPORTCOMMENT=,INPWR=-12.92,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10027,IPORTGROUP=OpenGroup,IPORTNAME=IN27,IPORTCOMMENT=,INPWR=-50.65,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10028,IPORTGROUP=OpenGroup,IPORTNAME=IN28,IPORTCOMMENT=,INPWR=-50.44,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10029,IPORTGROUP=OpenGroup,IPORTNAME=IN29,IPORTCOMMENT=,INPWR=-48.11,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10030,IPORTGROUP=OpenGroup,IPORTNAME=IN30,IPORTCOMMENT=,INPWR=-49.91,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10031,IPORTGROUP=OpenGroup,IPORTNAME=IN31,IPORTCOMMENT=,INPWR=-49.86,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10032,IPORTGROUP=OpenGroup,IPORTNAME=IN32,IPORTCOMMENT=,INPWR=-50.91,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
>
<

   BD0472 16-06-09 17:13:36
M  1 COMPLD
   "GGN:IPORTID=10033,IPORTGROUP=OpenGroup,IPORTNAME=IN33,IPORTCOMMENT=,INPWR=-50.65,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10034,IPORTGROUP=OpenGroup,IPORTNAME=IN34,IPORTCOMMENT=,INPWR=-50.08,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10035,IPORTGROUP=OpenGroup,IPORTNAME=IN35,IPORTCOMMENT=,INPWR=-50.42,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10036,IPORTGROUP=OpenGroup,IPORTNAME=IN36,IPORTCOMMENT=,INPWR=-50.38,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10037,IPORTGROUP=OpenGroup,IPORTNAME=IN37,IPORTCOMMENT=,INPWR=-10.25,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10038,IPORTGROUP=OpenGroup,IPORTNAME=IN38,IPORTCOMMENT=,INPWR=-12.19,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10039,IPORTGROUP=OpenGroup,IPORTNAME=IN39,IPORTCOMMENT=,INPWR=-51.07,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10040,IPORTGROUP=OpenGroup,IPORTNAME=IN40,IPORTCOMMENT=,INPWR=-50.91,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10041,IPORTGROUP=OpenGroup,IPORTNAME=IN41,IPORTCOMMENT=,INPWR=-50.38,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10042,IPORTGROUP=OpenGroup,IPORTNAME=IN42,IPORTCOMMENT=,INPWR=-50.18,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10043,IPORTGROUP=OpenGroup,IPORTNAME=IN43,IPORTCOMMENT=,INPWR=-50.98,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10044,IPORTGROUP=OpenGroup,IPORTNAME=IN44,IPORTCOMMENT=,INPWR=-50.54,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10045,IPORTGROUP=OpenGroup,IPORTNAME=IN45,IPORTCOMMENT=,INPWR=-50.24,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10046,IPORTGROUP=OpenGroup,IPORTNAME=IN46,IPORTCOMMENT=,INPWR=-50.24,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10047,IPORTGROUP=OpenGroup,IPORTNAME=IN47,IPORTCOMMENT=,INPWR=-51.12,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10048,IPORTGROUP=OpenGroup,IPORTNAME=IN48,IPORTCOMMENT=,INPWR=-50.61,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
>
<

   BD0472 16-06-09 17:13:36
M  1 COMPLD
   "GGN:IPORTID=10049,IPORTGROUP=OpenGroup,IPORTNAME=MC-1-1,IPORTCOMMENT=,INPWR=-49.14,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10050,IPORTGROUP=OpenGroup,IPORTNAME=MC-1-2,IPORTCOMMENT=,INPWR=-49.12,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10051,IPORTGROUP=OpenGroup,IPORTNAME=MC-1-3,IPORTCOMMENT=,INPWR=-51.20,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10052,IPORTGROUP=OpenGroup,IPORTNAME=MC-1-4,IPORTCOMMENT=,INPWR=-50.83,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10053,IPORTGROUP=OpenGroup,IPORTNAME=MC-2-1,IPORTCOMMENT=,INPWR=-50.48,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10054,IPORTGROUP=OpenGroup,IPORTNAME=MC-2-2,IPORTCOMMENT=,INPWR=-50.67,OPORTID=0,OPORTGROUP=,OPORTNAME=,OPORTCOMMENT=,OUTPWR=NA,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20001,OPORTGROUP=OpenGroup,OPORTNAME=OUT1,OPORTCOMMENT=,OUTPWR=-51.85,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20002,OPORTGROUP=OpenGroup,OPORTNAME=OUT2,OPORTCOMMENT=,OUTPWR=-51.09,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20003,OPORTGROUP=OpenGroup,OPORTNAME=OUT3,OPORTCOMMENT=,OUTPWR=-51.28,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20004,OPORTGROUP=OpenGroup,OPORTNAME=OUT4,OPORTCOMMENT=,OUTPWR=-51.14,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10004,IPORTGROUP=OpenGroup,IPORTNAME=IN4,IPORTCOMMENT=,INPWR=-11.93,OPORTID=20005,OPORTGROUP=OpenGroup,OPORTNAME=OUT5,OPORTCOMMENT=,OUTPWR=-13.51,SIGBAND=1550,PWRLOSS=1.58,CONNID=0,CONNNAME=IN4,CONNSTATE=steady,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER=admin"
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20006,OPORTGROUP=OpenGroup,OPORTNAME=OUT6,OPORTCOMMENT=,OUTPWR=-50.45,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20007,OPORTGROUP=OpenGroup,OPORTNAME=OUT7,OPORTCOMMENT=,OUTPWR=-51.46,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=10001,IPORTGROUP=OpenGroup,IPORTNAME=IN1,IPORTCOMMENT=,INPWR=-12.05,OPORTID=20008,OPORTGROUP=OpenGroup,OPORTNAME=OUT8,OPORTCOMMENT=,OUTPWR=-13.63,SIGBAND=1550,PWRLOSS=1.57,CONNID=0,CONNNAME=IN1,CONNSTATE=steady,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER=admin"
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20009,OPORTGROUP=OpenGroup,OPORTNAME=OUT9,OPORTCOMMENT=,OUTPWR=-51.25,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
>
<

   BD0472 16-06-09 17:13:36
M  1 COMPLD
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20010,OPORTGROUP=OpenGroup,OPORTNAME=OUT10,OPORTCOMMENT=,OUTPWR=-51.67,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20011,OPORTGROUP=OpenGroup,OPORTNAME=OUT11,OPORTCOMMENT=,OUTPWR=-51.56,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20012,OPORTGROUP=OpenGroup,OPORTNAME=OUT12,OPORTCOMMENT=,OUTPWR=-52.36,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20013,OPORTGROUP=OpenGroup,OPORTNAME=OUT13,OPORTCOMMENT=,OUTPWR=-51.69,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20014,OPORTGROUP=OpenGroup,OPORTNAME=OUT14,OPORTCOMMENT=,OUTPWR=-50.77,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20015,OPORTGROUP=OpenGroup,OPORTNAME=OUT15,OPORTCOMMENT=,OUTPWR=-49.08,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20016,OPORTGROUP=OpenGroup,OPORTNAME=OUT16,OPORTCOMMENT=,OUTPWR=-50.29,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20017,OPORTGROUP=OpenGroup,OPORTNAME=OUT17,OPORTCOMMENT=,OUTPWR=-49.93,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20018,OPORTGROUP=OpenGroup,OPORTNAME=OUT18,OPORTCOMMENT=,OUTPWR=-51.93,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20019,OPORTGROUP=OpenGroup,OPORTNAME=OUT19,OPORTCOMMENT=,OUTPWR=-52.77,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20020,OPORTGROUP=OpenGroup,OPORTNAME=OUT20,OPORTCOMMENT=,OUTPWR=-51.77,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20021,OPORTGROUP=OpenGroup,OPORTNAME=OUT21,OPORTCOMMENT=,OUTPWR=-50.55,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20022,OPORTGROUP=OpenGroup,OPORTNAME=OUT22,OPORTCOMMENT=,OUTPWR=-51.51,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20023,OPORTGROUP=OpenGroup,OPORTNAME=OUT23,OPORTCOMMENT=,OUTPWR=-51.21,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20024,OPORTGROUP=OpenGroup,OPORTNAME=OUT24,OPORTCOMMENT=,OUTPWR=-51.50,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20025,OPORTGROUP=OpenGroup,OPORTNAME=OUT25,OPORTCOMMENT=,OUTPWR=-51.55,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
>
<

   BD0472 16-06-09 17:13:36
M  1 COMPLD
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20026,OPORTGROUP=OpenGroup,OPORTNAME=OUT26,OPORTCOMMENT=,OUTPWR=-51.35,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20027,OPORTGROUP=OpenGroup,OPORTNAME=OUT27,OPORTCOMMENT=,OUTPWR=-51.70,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20028,OPORTGROUP=OpenGroup,OPORTNAME=OUT28,OPORTCOMMENT=,OUTPWR=-51.35,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20029,OPORTGROUP=OpenGroup,OPORTNAME=OUT29,OPORTCOMMENT=,OUTPWR=-50.73,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20030,OPORTGROUP=OpenGroup,OPORTNAME=OUT30,OPORTCOMMENT=,OUTPWR=-51.84,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20031,OPORTGROUP=OpenGroup,OPORTNAME=OUT31,OPORTCOMMENT=,OUTPWR=-49.83,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20032,OPORTGROUP=OpenGroup,OPORTNAME=OUT32,OPORTCOMMENT=,OUTPWR=-49.57,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20033,OPORTGROUP=OpenGroup,OPORTNAME=OUT33,OPORTCOMMENT=,OUTPWR=-50.56,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20034,OPORTGROUP=OpenGroup,OPORTNAME=OUT34,OPORTCOMMENT=,OUTPWR=-52.66,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20035,OPORTGROUP=OpenGroup,OPORTNAME=OUT35,OPORTCOMMENT=,OUTPWR=-51.67,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20036,OPORTGROUP=OpenGroup,OPORTNAME=OUT36,OPORTCOMMENT=,OUTPWR=-52.11,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20037,OPORTGROUP=OpenGroup,OPORTNAME=OUT37,OPORTCOMMENT=,OUTPWR=-49.84,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20038,OPORTGROUP=OpenGroup,OPORTNAME=OUT38,OPORTCOMMENT=,OUTPWR=-50.73,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20039,OPORTGROUP=OpenGroup,OPORTNAME=OUT39,OPORTCOMMENT=,OUTPWR=-51.31,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20040,OPORTGROUP=OpenGroup,OPORTNAME=OUT40,OPORTCOMMENT=,OUTPWR=-49.71,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20041,OPORTGROUP=OpenGroup,OPORTNAME=OUT41,OPORTCOMMENT=,OUTPWR=-50.56,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
>
<

   BD0472 16-06-09 17:13:36
M  1 COMPLD
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20042,OPORTGROUP=OpenGroup,OPORTNAME=OUT42,OPORTCOMMENT=,OUTPWR=-51.80,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20043,OPORTGROUP=OpenGroup,OPORTNAME=OUT43,OPORTCOMMENT=,OUTPWR=-51.56,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20044,OPORTGROUP=OpenGroup,OPORTNAME=OUT44,OPORTCOMMENT=,OUTPWR=-51.60,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20045,OPORTGROUP=OpenGroup,OPORTNAME=OUT45,OPORTCOMMENT=,OUTPWR=-50.77,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20046,OPORTGROUP=OpenGroup,OPORTNAME=OUT46,OPORTCOMMENT=,OUTPWR=-50.37,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20047,OPORTGROUP=OpenGroup,OPORTNAME=OUT47,OPORTCOMMENT=,OUTPWR=-51.43,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20048,OPORTGROUP=OpenGroup,OPORTNAME=OUT48,OPORTCOMMENT=,OUTPWR=-51.10,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20049,OPORTGROUP=OpenGroup,OPORTNAME=MC-1,OPORTCOMMENT=,OUTPWR=-50.66,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
   "GGN:IPORTID=0,IPORTGROUP=,IPORTNAME=,IPORTCOMMENT=,INPWR=NA,OPORTID=20050,OPORTGROUP=OpenGroup,OPORTNAME=MC-2,OPORTCOMMENT=,OUTPWR=-49.72,SIGBAND=1550,PWRLOSS=NA,CONNID=0,CONNNAME=,CONNSTATE=single,CONNCAUSE=none,CONNLOCK=0,CONNLOCKUSER="
;
"""
custom_port_pairing = {
    "1": "48",
    "2": "3"
}
port_list = device_data['port_list'].split("\n")
port_map_list = device_data["connections_map"].split("\n")
_mapping_info = {}
address_prefix = '10.10.1.1'
result_list = []

logical_port_map = dict()
temp_logical_port_map = dict()
for port_data in port_list:
    port_info_match = re.search(r"PORTID=(?P<id>\d+).*PORTNAME=(?P<name>(IN|OUT)\d+)" +
                                ".*PORTHEALTH=(?P<state>good|bad)", port_data, re.DOTALL)
    if port_info_match is not None:
        port_info_dict = port_info_match.groupdict()
        logical_port_id = re.sub('(IN|OUT)', '', port_info_dict["name"])
        if logical_port_id not in temp_logical_port_map.keys():
            temp_logical_port_map[logical_port_id] = {}
        if port_info_dict["state"].lower() == "good":
            port_state = "Enable"
        else:
            port_state = "Disable"

        temp_logical_port_map[logical_port_id]['state'] = port_state

        if 'in' in port_info_dict["name"].lower():
            temp_logical_port_map[logical_port_id]['in'] = port_info_dict['id']
        else:
            temp_logical_port_map[logical_port_id]['out'] = port_info_dict['id']

        if 'in' in logical_port_map[logical_port_id] and 'out' in logical_port_map[logical_port_id]:
            logical_port_map[logical_port_id]['port_address'] = '{0}-{1}'.format(logical_port_id,
                                                                                 logical_port_id)

    if 'in' in logical_port_map[logical_port_id] and 'out' in logical_port_map[logical_port_id]:
        logical_port_map[logical_port_id]['port_address'] = '{0}-{1}'.format(logical_port_id,
                                                                             logical_port_id)

for port_data in port_map_list:
    port_map_match = re.search(r"IPORTID=(?P<src_port>\d+).*IPORTNAME=(?P<src_port_name>\S+),IP.*" +
                               "OPORTID=(?P<dst_port>\d+).*OPORTNAME=(?P<dst_port_name>\S+),OP.*",
                               port_data, re.DOTALL)
    if port_map_match is not None:
        port_map_dict = port_map_match.groupdict()
        src_logical_port_id = re.sub('(IN|OUT)', '', port_map_dict["src_port_name"])
        dst_logical_port_id = re.sub('(IN|OUT)', '', port_map_dict["dst_port_name"])
        if src_logical_port_id in logical_port_map.keys() \
                and dst_logical_port_id in logical_port_map.keys():
            _mapping_info[src_logical_port_id] = dst_logical_port_id

for logical_port_index, logical_port_data in logical_port_map.iteritems():
    port_resource_info = ResourceInfo()
    port_resource_info.set_depth(1)
    port_resource_info.set_index(logical_port_data['port_address'])
    port_resource_info.set_model_name('adadadad')
    if logical_port_index in _mapping_info:
        port_resource_info.set_mapping(
            address_prefix + logical_port_map[_mapping_info[logical_port_index]]['port_address'])
    port_resource_info.add_attribute("State", logical_port_data['state'])
    port_resource_info.add_attribute("Protocol Type", 0)
    result_list.append((logical_port_index, port_resource_info))

print result_list
